### ISSUE TITLE
The `per_page` field only list down 20 per page

### ISSUE THREAD

**Issue by Pushkarmondal** [civo/civogo#202] opened 2024-09-01 07:19 UTC
The `per_page` fields list down only 20, if someone create greater than 20 list, it should be helpful if it shows all the list at a single page.

**Comment by uzaxirr** [comment] 2024-09-05 06:18
feel free to raise PR if you can do it

**Comment by uzaxirr** [comment] 2024-09-10 07:43
duplicate of #206

**Closed by uzaxirr** 2024-09-10 07:43 UTC
